name: Email on deploy
description: Send email on deploy success or failure
inputs:
  path_to_package_json:
    description: Path to package.json file in repo
    default: './package.json'
  mailjet_public:
    description: Mailjet Public Key
    required: true
  mailjet_private:
    description: Mailjet Private Key
    required: true
  from_email:
    description: Email address to use as the sender
    required: true
  from_name:
    description: Name of sender
    required: true
  send_to:
    description: JSON of receipients based on deploy status
    required: true
runs:
  using: node12
  main: main.js