name: Email on deploy
description: Send email on deploy success or failure
inputs:
  path_to_package_json:
    description: Path to package.json file in repo
    default: './package.json'
  commit_message:
    default: ${{ github.event.head_commit.message }}
  mailjet_public:
    description: Mailjet Public Key
    required: true
  mailjet_private:
    description: Mailjet Private Key
    required: true
runs:
  using: node12
  main: main.js